function h_surf = vutil_view_surf(vertices, faces, rgb, varargin)
    default_cell = {'tag','surface','parameter'};
    params = util_extract_inputs(default_cell, varargin);

    h_surf = patch(...,
        'faces',faces,...
        'vertices',vertices,...
        'edgecolor','none',...
        'facecolor','interp',...
        'facevertexcdata',rgb,...
        'tag',params.tag);
end